service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: aggutie-sso
  ecr:
    images:
      appimage:
        uri: 590184075857.dkr.ecr.us-east-1.amazonaws.com/node20lambda:latest

functions:
  nextjsApp:
    image:
      name: appimage
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
    target: "node20"
    external: [".next"]
    packager: "npm"
    exclude: ["aws-sdk"]
