org: agdev
service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: aggutie-sso

functions:
  nextjsApp:
<<<<<<< HEAD
    handler: handler.js
=======
    image: 590184075857.dkr.ecr.us-east-1.amazonaws.com/node20lambda:latest
>>>>>>> parent of 558a2a4c (more config)
    events:
      - http:
          path: /handler.s
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
