# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: agdev
service: blog_news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-next.js

functions:
  nextjsApp:
    image:
      name: node20lambda
    events:
      - http:
          path: /
          method: get
      - http:
          path: /_next/{proxy+}
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-next.js

custom:
  nextConfigDir: ./
