org: agdev
app: blognews
service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
        - lambda:UpdateFunctionConfiguration
        - lambda:UpdateFunctionCode
        - s3:*
        - cloudformation:*
      Resource: "*"
  role: arn:aws:iam::590184075857:role/SFSetup-480d2b

plugins:
  - serverless-next.js

custom:
  nextConfigDir: ./

functions:
  app:
    handler: serverless-next.handler
    events:
      - http: "ANY /"
      - http: "ANY /{proxy+}"
