org: agdev
service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: aggutie-sso

functions:
  nextjsApp:
    image: 590184075857.dkr.ecr.us-east-1.amazonaws.com/node20lambda:latest
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  esbuild:
    bundle: true
    minify: false
