# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: agdev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: blognews
service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 # You can choose your preferred AWS region

plugins:
  - serverless-next.js

custom:
  nextConfigDir: ./

functions:
  app:
    handler: serverless-next.handler
    events:
      - http: "ANY /"
      - http: "ANY /{proxy+}"
