org: agdev
service: blog-news

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: aggutie-sso

functions:
  nextjsApp:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  esbuild:
    bundle: true
    minify: false
